name: aressa_commerce
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.7
  showcaseview: ^1.1.1
  another_flushbar: ^1.10.24
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/asset/image/review/ava.png
    - lib/asset/image/review/rp1.png
    - lib/asset/image/review/rp2.png
    - lib/asset/image/review/rp3.png
    - lib/asset/image/banner/bannerFlashSale.png
    - lib/asset/image/banner/bannerNewSeason.png
    - lib/asset/image/banner/bannerSuperPromo.png
    - lib/asset/image/promotionDummy.png
    - lib/asset/image/home/indonesianFlag.png
    - lib/asset/image/home/britishFlag.png
    - lib/asset/image/home/TurkeyFlag.png
    - lib/asset/image/home/love.png
    - lib/asset/image/home/bikini.png
    - lib/asset/image/home/dress.png
    - lib/asset/image/home/DressNew.png
    - lib/asset/image/home/manBag.png
    - lib/asset/image/home/manWorkEqNew.png
    - lib/asset/image/home/manPants.png
    - lib/asset/image/home/manPantsNew.png
    - lib/asset/image/home/manShoes.png
    - lib/asset/image/home/manShoesNew.png
    - lib/asset/image/home/manUnderwear.png
    - lib/asset/image/home/manUnderwareNew.png
    - lib/asset/image/home/notification.png
    - lib/asset/image/home/manShirtNew.png
    - lib/asset/image/home/shirt.png
    - lib/asset/image/home/skirt.png
    - lib/asset/image/home/skirtNew.png
    - lib/asset/image/home/tshirt.png
    - lib/asset/image/home/manTshirtNew.png
    - lib/asset/image/home/womanBag.png
    - lib/asset/image/home/womanBagNew.png
    - lib/asset/image/home/womanPants.png
    - lib/asset/image/home/womanPantsNew.png
    - lib/asset/image/home/womanShoes.png
    - lib/asset/image/home/womanShoesNew.png
    - lib/asset/image/home/womanTshirt.png
    - lib/asset/image/home/womanTshirtNew.png
    - lib/asset/image/home/PromotionImage2.png
    - lib/asset/image/home/more.png
    - lib/asset/image/home/Search.png
    - lib/asset/image/home/logo.png
    - lib/asset/image/home/Google.png
    - lib/asset/image/home/Facebook.png
    - lib/asset/image/home/sepatuBiru.png
    - lib/asset/image/home/sepatuMerah.png
    - lib/asset/json/flashSale.json
    - lib/asset/json/megaSale.json
    - lib/asset/json/recommended.json
    - lib/asset/json/category.json
    - lib/asset/json/product.json
    - lib/asset/image/product/speed3.jpeg
    - lib/asset/image/product/speed3v1.jpeg
    - lib/asset/image/product/speed3v2.jpeg
    - lib/asset/image/product/speed3v3.jpeg
    - lib/asset/image/product/nikeBasketballShoes.jpg
    - lib/asset/image/product/nikeBasketballShoes2.jpg
    - lib/asset/image/product/nikeBasketballShoes3.jpg
    - lib/asset/image/product/nikeBasketballShoes4.jpg
    - lib/asset/image/product/menCasualShoes.jpg
    - lib/asset/image/product/menCasualShoes2.jpg
    - lib/asset/image/product/menCasualShoes3.jpg
    - lib/asset/image/product/menCasualShoes4.jpg
    - lib/asset/image/product/europeanSportMenShoes.jpg
    - lib/asset/image/product/europeanSportMenShoes2.jpg
    - lib/asset/image/product/europeanSportMenShoes3.jpg
    - lib/asset/image/product/europeanSportMenShoes4.jpg
    - lib/asset/image/product/walkingSneaker.jpg
    - lib/asset/image/product/walkingSneaker2.jpg
    - lib/asset/image/product/walkingSneaker3.jpg
    - lib/asset/image/product/walkingSneaker4.jpg
    - lib/asset/image/product/fashionTshirtMensWhite.jpg
    - lib/asset/image/product/fashionTshirtMensWhite2.jpg
    - lib/asset/image/product/fashionTshirtMensWhite3.jpg
    - lib/asset/image/product/fashionTshirtMensWhite4.jpg
    - lib/asset/image/product/summerMenTshirt.jpg
    - lib/asset/image/product/summerMenTshirt2.png
    - lib/asset/image/product/summerMenTshirt3.png
    - lib/asset/image/product/summerMenTshirt4.jpg
    - lib/asset/image/product/eagleMenTshirt.jpg
    - lib/asset/image/product/eagleMenTshirt2.jpg
    - lib/asset/image/product/eagleMenTshirt3.jpg
    - lib/asset/image/product/eagleMenTshirt4.jpg
    - lib/asset/image/product/parisMenTshirt.jpg
    - lib/asset/image/product/parisMenTshirt2.png
    - lib/asset/image/product/parisMenTshirt3.png
    - lib/asset/image/product/parisMenTshirt4.png
    - lib/asset/image/product/graphicMenTshirt.jpg
    - lib/asset/image/product/graphicMenTshirt2.jpg
    - lib/asset/image/product/graphicMenTshirt3.jpg
    - lib/asset/image/product/graphicMenTshirt4.jpg
    - lib/asset/image/home/notFound.png
    - lib/asset/image/product/menWorkWearJacket.jpg
    - lib/asset/image/product/menWorkWearJacket2.jpg
    - lib/asset/image/product/menWorkWearJacket3.jpg
    - lib/asset/image/product/menWorkWearJacket4.jpg
    - lib/asset/image/product/menWorkShoes.jpg
    - lib/asset/image/product/menWorkShoes2.jpg
    - lib/asset/image/product/menWorkShoes3.jpg
    - lib/asset/image/product/menWorkShoes4.jpg
    - lib/asset/image/product/mensUvJacket.jpg
    - lib/asset/image/product/mensUvJacket2.jpg
    - lib/asset/image/product/mensUvJacket3.jpg
    - lib/asset/image/product/mensUvJacket4.jpg
    - lib/asset/image/product/mensArmorCombat.jpg
    - lib/asset/image/product/mensArmorCombat2.jpg
    - lib/asset/image/product/mensArmorCombat3.jpg
    - lib/asset/image/product/mensArmorCombat4.jpg
    - lib/asset/image/product/mensSafetyJacket.jpg
    - lib/asset/image/product/mensSafetyJacket2.jpg
    - lib/asset/image/product/mensSafetyJacket3.jpg
    - lib/asset/image/product/mensSafetyJacket4.jpg
    - lib/asset/image/product/menCasualShirt.png
    - lib/asset/image/product/menCasualShirt2.png
    - lib/asset/image/product/menCasualShirt3.png
    - lib/asset/image/product/menCasualShirt4.png
    - lib/asset/image/product/koreanMenShirt.jpg
    - lib/asset/image/product/koreanMenShirt2.jpg
    - lib/asset/image/product/koreanMenShirt3.jpg
    - lib/asset/image/product/koreanMenShirt4.jpg
    - lib/asset/image/product/hawaiMenShirt.jpg
    - lib/asset/image/product/hawaiMenShirt2.jpg
    - lib/asset/image/product/hawaiMenShirt3.jpg
    - lib/asset/image/product/hawaiMenShirt4.jpg
    - lib/asset/image/product/businessCasualShirt.jpg
    - lib/asset/image/product/businessCasualShirt2.jpg
    - lib/asset/image/product/businessCasualShirt3.jpg
    - lib/asset/image/product/businessCasualShirt4.jpg
    - lib/asset/image/product/beachMenShirt.jpg
    - lib/asset/image/product/beachMenShirt2.jpg
    - lib/asset/image/product/beachMenShirt3.jpg
    - lib/asset/image/product/beachMenShirt4.jpg
    - lib/asset/image/product/casualMenPants.jpg
    - lib/asset/image/product/casualMenPants2.jpg
    - lib/asset/image/product/casualMenPants3.jpg
    - lib/asset/image/product/casualMenPants4.jpg
    - lib/asset/image/product/manJoggersPants.jpg
    - lib/asset/image/product/manJoggersPants2.jpg
    - lib/asset/image/product/manJoggersPants3.jpg
    - lib/asset/image/product/manJoggersPants4.jpg
    - lib/asset/image/product/nylonManPants.jpg
    - lib/asset/image/product/nylonManPants2.jpg
    - lib/asset/image/product/nylonManPants3.jpg
    - lib/asset/image/product/nylonManPants4.jpg
    - lib/asset/image/product/cargoPantsForMen.jpg
    - lib/asset/image/product/cargoPantsForMen2.jpg
    - lib/asset/image/product/cargoPantsForMen3.jpg
    - lib/asset/image/product/cargoPantsForMen4.jpg
    - lib/asset/image/product/menStreetwear.png
    - lib/asset/image/product/menStreetwear2.png
    - lib/asset/image/product/menStreetwear3.png
    - lib/asset/image/product/menStreetwear4.png
    - lib/asset/image/product/designerSwimsuitsBikini.jpg
    - lib/asset/image/product/designerSwimsuitsBikini2.jpg
    - lib/asset/image/product/designerSwimsuitsBikini3.jpg
    - lib/asset/image/product/designerSwimsuitsBikini4.jpg
    - lib/asset/image/product/customSexyBikiniSwimwear.jpg
    - lib/asset/image/product/customSexyBikiniSwimwear2.png
    - lib/asset/image/product/customSexyBikiniSwimwear3.jpg
    - lib/asset/image/product/customSexyBikiniSwimwear4.png
    - lib/asset/image/product/bikiniYoungGirlSwimwear.jpg
    - lib/asset/image/product/bikiniYoungGirlSwimwear2.jpg
    - lib/asset/image/product/bikiniYoungGirlSwimwear3.jpg
    - lib/asset/image/product/bikiniYoungGirlSwimwear4.jpg
    - lib/asset/image/product/bikinisBlingSwimsuit.jpg
    - lib/asset/image/product/bikinisBlingSwimsuit2.jpg
    - lib/asset/image/product/bikinisBlingSwimsuit3.jpg
    - lib/asset/image/product/bikinisBlingSwimsuit4.jpg
    - lib/asset/image/product/customizedBikini.png
    - lib/asset/image/product/customizedBikini2.png
    - lib/asset/image/product/customizedBikini3.png
    - lib/asset/image/product/customizedBikini4.png
    - lib/asset/image/product/womenMidlongSkirt.jpg
    - lib/asset/image/product/womenMidlongSkirt2.jpg
    - lib/asset/image/product/womenMidlongSkirt3.jpg
    - lib/asset/image/product/womenMidlongSkirt4.jpg
    - lib/asset/image/product/summerSkirt.jpg
    - lib/asset/image/product/summerSkirt2.jpg
    - lib/asset/image/product/summerSkirt3.jpg
    - lib/asset/image/product/summerSkirt4.jpg
    - lib/asset/image/product/wrapSkirt.jpg
    - lib/asset/image/product/wrapSkirt2.jpg
    - lib/asset/image/product/wrapSkirt3.jpg
    - lib/asset/image/product/wrapSkirt4.jpg
    - lib/asset/image/product/midiSkirtPartyHoliday.jpg
    - lib/asset/image/product/midiSkirtPartyHoliday2.jpg
    - lib/asset/image/product/midiSkirtPartyHoliday3.png
    - lib/asset/image/product/midiSkirtPartyHoliday4.png
    - lib/asset/image/product/longPalazzoPantSkirt.jpg
    - lib/asset/image/product/longPalazzoPantSkirt2.jpg
    - lib/asset/image/product/longPalazzoPantSkirt3.jpg
    - lib/asset/image/product/longPalazzoPantSkirt4.jpg
    - lib/asset/image/product/dressWomanWithSlit.jpg
    - lib/asset/image/product/dressWomanWithSlit2.jpg
    - lib/asset/image/product/dressWomanWithSlit3.jpg
    - lib/asset/image/product/dressWomanWithSlit4.jpg
    - lib/asset/image/product/casualDress.jpg
    - lib/asset/image/product/casualDress2.jpg
    - lib/asset/image/product/casualDress3.jpg
    - lib/asset/image/product/casualDress4.jpg
    - lib/asset/image/product/elegantWomenDress.jpg
    - lib/asset/image/product/elegantWomenDress2.jpg
    - lib/asset/image/product/elegantWomenDress3.jpg
    - lib/asset/image/product/elegantWomenDress4.jpg
    - lib/asset/image/product/summerWomenSlim.jpg
    - lib/asset/image/product/summerWomenSlim2.jpg
    - lib/asset/image/product/summerWomenSlim3.jpg
    - lib/asset/image/product/summerWomenSlim4.jpg
    - lib/asset/image/product/longCasualDresses.jpg
    - lib/asset/image/product/longCasualDresses2.jpg
    - lib/asset/image/product/longCasualDresses3.jpg
    - lib/asset/image/product/longCasualDresses4.jpg
    - lib/asset/image/product/joggerTrousersWomen.jpg
    - lib/asset/image/product/joggerTrousersWomen2.jpg
    - lib/asset/image/product/joggerTrousersWomen3.jpg
    - lib/asset/image/product/joggerTrousersWomen4.jpg
    - lib/asset/image/product/springCasualCustomWomen.jpg
    - lib/asset/image/product/springCasualCustomWomen2.jpg
    - lib/asset/image/product/springCasualCustomWomen3.jpg
    - lib/asset/image/product/springCasualCustomWomen4.jpg
    - lib/asset/image/product/leggingsCustomPrintedWomen.jpg
    - lib/asset/image/product/leggingsCustomPrintedWomen2.jpg
    - lib/asset/image/product/leggingsCustomPrintedWomen3.jpg
    - lib/asset/image/product/leggingsCustomPrintedWomen4.jpg
    - lib/asset/image/product/longWomenDressPants.png
    - lib/asset/image/product/longWomenDressPants2.jpg
    - lib/asset/image/product/longWomenDressPants3.jpg
    - lib/asset/image/product/longWomenDressPants4.jpg
    - lib/asset/image/product/camouflagePantsForWomen.jpg
    - lib/asset/image/product/camouflagePantsForWomen2.jpg
    - lib/asset/image/product/camouflagePantsForWomen3.jpg
    - lib/asset/image/product/camouflagePantsForWomen4.jpg
    - lib/asset/image/product/cottonBoxersPackSet.jpg
    - lib/asset/image/product/cottonBoxersPackSet2.jpg
    - lib/asset/image/product/cottonBoxersPackSet3.jpg
    - lib/asset/image/product/cottonBoxersPackSet4.jpg
    - lib/asset/image/product/seamlessMenUnderwear.jpg
    - lib/asset/image/product/seamlessMenUnderwear2.jpg
    - lib/asset/image/product/seamlessMenUnderwear3.jpg
    - lib/asset/image/product/seamlessMenUnderwear4.jpg
    - lib/asset/image/product/underwearSportComfortable.jpg
    - lib/asset/image/product/underwearSportComfortable2.jpg
    - lib/asset/image/product/underwearSportComfortable3.jpg
    - lib/asset/image/product/underwearSportComfortable4.jpg
    - lib/asset/image/product/vendorUnderwear.jpg
    - lib/asset/image/product/vendorUnderwear2.jpg
    - lib/asset/image/product/vendorUnderwear3.jpg
    - lib/asset/image/product/vendorUnderwear4.jpg
    - lib/asset/image/product/longLegUnderwear.jpg
    - lib/asset/image/product/longLegUnderwear2.jpg
    - lib/asset/image/product/longLegUnderwear3.jpg
    - lib/asset/image/product/longLegUnderwear4.jpg
    - lib/asset/image/product/customSummerPopular.jpg
    - lib/asset/image/product/customSummerPopular2.jpg
    - lib/asset/image/product/customSummerPopular3.jpg
    - lib/asset/image/product/customSummerPopular4.jpg
    - lib/asset/image/product/cropTopsTshirtWomen.jpg
    - lib/asset/image/product/cropTopsTshirtWomen2.jpg
    - lib/asset/image/product/cropTopsTshirtWomen3.jpg
    - lib/asset/image/product/cropTopsTshirtWomen4.jpg
    - lib/asset/image/product/oversizedTopsWomenTShirt.jpg
    - lib/asset/image/product/oversizedTopsWomenTShirt2.jpg
    - lib/asset/image/product/oversizedTopsWomenTShirt3.jpg
    - lib/asset/image/product/oversizedTopsWomenTShirt4.jpg
    - lib/asset/image/product/warmSlimFemaleShirt.png
    - lib/asset/image/product/warmSlimFemaleShirt2.jpg
    - lib/asset/image/product/warmSlimFemaleShirt3.jpg
    - lib/asset/image/product/warmSlimFemaleShirt4.jpg
    - lib/asset/image/product/whiteTshirtFemale.jpg
    - lib/asset/image/product/whiteTshirtFemale2.jpg
    - lib/asset/image/product/whiteTshirtFemale3.jpg
    - lib/asset/image/product/whiteTshirtFemale4.jpg
    - lib/asset/image/product/womenKawaiiPinkBackpack.jpg
    - lib/asset/image/product/womenKawaiiPinkBackpack2.jpg
    - lib/asset/image/product/womenKawaiiPinkBackpack3.jpg
    - lib/asset/image/product/womenKawaiiPinkBackpack4.jpg
    - lib/asset/image/product/highCapacityWomenBackpacks.jpg
    - lib/asset/image/product/highCapacityWomenBackpacks2.jpg
    - lib/asset/image/product/highCapacityWomenBackpacks3.jpg
    - lib/asset/image/product/highCapacityWomenBackpacks4.jpg
    - lib/asset/image/product/womenHandBagsLuxury.jpg
    - lib/asset/image/product/womenHandBagsLuxury2.jpg
    - lib/asset/image/product/womenHandBagsLuxury3.jpg
    - lib/asset/image/product/womenHandBagsLuxury4.jpg
    - lib/asset/image/product/classicWomenHandBags.jpg
    - lib/asset/image/product/classicWomenHandBags2.jpg
    - lib/asset/image/product/classicWomenHandBags3.jpg
    - lib/asset/image/product/classicWomenHandBags4.jpg
    - lib/asset/image/product/handbagCasualShoulder.jpg
    - lib/asset/image/product/handbagCasualShoulder2.jpg
    - lib/asset/image/product/handbagCasualShoulder3.jpg
    - lib/asset/image/product/handbagCasualShoulder4.jpg
    - lib/asset/image/product/womenSummerSexyHighHeel.jpg
    - lib/asset/image/product/womenSummerSexyHighHeel2.jpg
    - lib/asset/image/product/womenSummerSexyHighHeel3.jpg
    - lib/asset/image/product/womenSummerSexyHighHeel4.jpg
    - lib/asset/image/product/sexyShoesLadiesHighHeels.jpg
    - lib/asset/image/product/sexyShoesLadiesHighHeels2.jpg
    - lib/asset/image/product/sexyShoesLadiesHighHeels3.jpg
    - lib/asset/image/product/sexyShoesLadiesHighHeels4.jpg
    - lib/asset/image/product/buckleLadiesHighHeels.jpg
    - lib/asset/image/product/buckleLadiesHighHeels2.jpg
    - lib/asset/image/product/buckleLadiesHighHeels3.jpg
    - lib/asset/image/product/buckleLadiesHighHeels4.jpg
    - lib/asset/image/product/pumpShoesHighHeels.jpg
    - lib/asset/image/product/pumpShoesHighHeels2.jpg
    - lib/asset/image/product/pumpShoesHighHeels3.jpg
    - lib/asset/image/product/pumpShoesHighHeels4.jpg
    - lib/asset/image/product/womenSandals2021NewHeels.jpg
    - lib/asset/image/product/womenSandals2021NewHeels2.jpg
    - lib/asset/image/product/womenSandals2021NewHeels3.jpg
    - lib/asset/image/product/womenSandals2021NewHeels4.jpg
  fonts:
    - family: PoppinsBlack
      fonts:
         - asset: lib/asset/fonts/Poppins/Poppins-Black.ttf
    - family: PoppinsBlackItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-BlackItalic.ttf
    - family: PoppinsBold
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Bold.ttf
    - family: PoppinsBoldItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-BoldItalic.ttf
    - family: PoppinsExtraBold
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ExtraBold.ttf
    - family: PoppinsExtraBoldItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
    - family: PoppinsExtraLight
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ExtraLight.ttf
    - family: PoppinsExtraLightItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ExtraLightItalic.ttf
    - family: PoppinsItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Italic.ttf
    - family: PoppinsLight
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Light.ttf
    - family: PoppinsLightItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-LightItalic.ttf
    - family: PoppinsMedium
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Medium.ttf
    - family: PoppinsMediumItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-MediumItalic.ttf
    - family: PoppinsRegular
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-SemiBold.ttf
    - family: PoppinsSemiBoldItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-SemiBoldItalic.ttf
    - family: PoppinsThin
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Thin.ttf
    - family: PoppinsThinItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ThinItalic.ttf

flutter_intl:
  main_locale: en_US
  enabled: true
