name: aressa_commerce
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/asset/image/promotionDummy.png
    - lib/asset/image/home/love.png
    - lib/asset/image/home/bikini.png
    - lib/asset/image/home/dress.png
    - lib/asset/image/home/manBag.png
    - lib/asset/image/home/manPants.png
    - lib/asset/image/home/manShoes.png
    - lib/asset/image/home/manUnderwear.png
    - lib/asset/image/home/notification.png
    - lib/asset/image/home/shirt.png
    - lib/asset/image/home/skirt.png
    - lib/asset/image/home/tshirt.png
    - lib/asset/image/home/womanBag.png
    - lib/asset/image/home/womanPants.png
    - lib/asset/image/home/womanShoes.png
    - lib/asset/image/home/womanTshirt.png

