name: aressa_commerce
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.7
  showcaseview: ^1.1.1
  another_flushbar: ^1.10.24
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/asset/image/review/ava.png
    - lib/asset/image/review/rp1.png
    - lib/asset/image/review/rp2.png
    - lib/asset/image/review/rp3.png
    - lib/asset/image/category/alatShalat.png
    - lib/asset/image/category/bahanMakanan.png
    - lib/asset/image/category/bajuTradisional.png
    - lib/asset/image/category/batik.png
    - lib/asset/image/category/furnish.png
    - lib/asset/image/category/sendalSepatu.png
    - lib/asset/image/banner/bannerFlashSale.png
    - lib/asset/image/banner/bannerNewSeason.png
    - lib/asset/image/banner/bannerSuperPromo.png
    - lib/asset/image/promotionDummy.png
    - lib/asset/image/home/indonesianFlag.png
    - lib/asset/image/home/britishFlag.png
    - lib/asset/image/home/TurkeyFlag.png
    - lib/asset/image/home/love.png
    - lib/asset/image/home/notification.png
    - lib/asset/image/home/PromotionImage2.png
    - lib/asset/image/home/more.png
    - lib/asset/image/home/Search.png
    - lib/asset/image/home/logo.png
    - lib/asset/image/home/Google.png
    - lib/asset/image/home/Facebook.png
    - lib/asset/image/home/sepatuBiru.png
    - lib/asset/image/home/sepatuMerah.png
    - lib/asset/image/home/headerBg.png
    - lib/asset/json/flashSale.json
    - lib/asset/json/megaSale.json
    - lib/asset/json/recommended.json
    - lib/asset/json/category.json
    - lib/asset/json/product.json
    - lib/asset/image/home/notFound.png
    - lib/asset/image/product/adinataBatik1.jpeg
    - lib/asset/image/product/adinataBatik2.jpeg
    - lib/asset/image/product/adinataBatik3.jpeg
    - lib/asset/image/product/batikAksa1.jpeg
    - lib/asset/image/product/batikAksa2.jpeg
    - lib/asset/image/product/batikAksa3.jpeg
    - lib/asset/image/product/taraBatik1.jpeg
    - lib/asset/image/product/taraBatik2.jpeg
    - lib/asset/image/product/taraBatik3.jpeg
    - lib/asset/image/product/batikFirst1.jpeg
    - lib/asset/image/product/batikFirst2.jpeg
    - lib/asset/image/product/riantiBatik1.jpeg
    - lib/asset/image/product/riantiBatik2.jpeg
    - lib/asset/image/product/riantiBatik3.jpeg
    - lib/asset/image/product/janaharaMukena.jpeg
    - lib/asset/image/product/janaharaMukena2.jpeg
    - lib/asset/image/product/novellaBlack1.jpeg
    - lib/asset/image/product/novellaBlack2.jpeg
    - lib/asset/image/product/novellaMukena1.jpeg
    - lib/asset/image/product/novellaMukena2.jpeg
    - lib/asset/image/product/sistaMukena1.jpeg
    - lib/asset/image/product/sistaMukena2.jpeg
    - lib/asset/image/product/sistaMukena3.jpeg
    - lib/asset/image/product/sajadah1.jpeg
    - lib/asset/image/product/sajadah2.jpeg
    - lib/asset/image/product/sandalKayu1.jpg
    - lib/asset/image/product/sandalKayu2.jpg
    - lib/asset/image/product/sandalKayu3.jpg
    - lib/asset/image/product/sandalPlastik1.jpg
    - lib/asset/image/product/sandalPlastik2.jpg
    - lib/asset/image/product/sandalPlastik3.jpg
    - lib/asset/image/product/sandalKayu4.jpg
    - lib/asset/image/product/sandalKayu5.jpg
    - lib/asset/image/product/sandalKayu6.jpg
    - lib/asset/image/product/sepatuKain1.jpg
    - lib/asset/image/product/sepatuKain2.jpg
    - lib/asset/image/product/sepatuKain3.jpg
    - lib/asset/image/product/sepatuKain4.jpg
    - lib/asset/image/product/sepatuKain5.jpg
    - lib/asset/image/product/furnishKayu1.jpg
    - lib/asset/image/product/furnishKayu2.jpg
    - lib/asset/image/product/furnishKayu3.jpg
    - lib/asset/image/product/furnishKayu4.jpg
    - lib/asset/image/product/furnishKayu5.jpg
    - lib/asset/image/product/furnishKayu6.jpg
    - lib/asset/image/product/furnishKayu7.jpg
    - lib/asset/image/product/furnishKayu8.jpg
    - lib/asset/image/product/furnishKayu9.jpg
    - lib/asset/image/product/furnishKayu10.jpg
    - lib/asset/image/product/furnishKayu11.jpg
    - lib/asset/image/product/furnishKayu12.jpg
    - lib/asset/image/product/furnishKayu13.jpg
    - lib/asset/image/product/furnishKayu14.jpg
    - lib/asset/image/product/furnishKayu15.jpg
  fonts:
    - family: PoppinsBlack
      fonts:
         - asset: lib/asset/fonts/Poppins/Poppins-Black.ttf
    - family: PoppinsBlackItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-BlackItalic.ttf
    - family: PoppinsBold
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Bold.ttf
    - family: PoppinsBoldItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-BoldItalic.ttf
    - family: PoppinsExtraBold
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ExtraBold.ttf
    - family: PoppinsExtraBoldItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
    - family: PoppinsExtraLight
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ExtraLight.ttf
    - family: PoppinsExtraLightItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ExtraLightItalic.ttf
    - family: PoppinsItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Italic.ttf
    - family: PoppinsLight
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Light.ttf
    - family: PoppinsLightItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-LightItalic.ttf
    - family: PoppinsMedium
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Medium.ttf
    - family: PoppinsMediumItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-MediumItalic.ttf
    - family: PoppinsRegular
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-SemiBold.ttf
    - family: PoppinsSemiBoldItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-SemiBoldItalic.ttf
    - family: PoppinsThin
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-Thin.ttf
    - family: PoppinsThinItalic
      fonts:
          - asset: lib/asset/fonts/Poppins/Poppins-ThinItalic.ttf

flutter_intl:
  main_locale: en_US
  enabled: true
